# Generated by Django 5.0.1 on 2024-01-12 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, 'engineer'), (1, 'product'), (2, 'operation'), (3, 'design')], verbose_name='Job Type')),
                ('job_name', models.CharField(max_length=250, verbose_name='Job Name')),
                ('job_city', models.SmallIntegerField(choices=[(0, 'NYC'), (1, 'DC'), (2, 'SF')], verbose_name='Job Location')),
                ('job_responsibilities', models.TextField(max_length=1024, verbose_name='Job Responsibilites')),
                ('job_requirements', models.TextField(max_length=200, verbose_name='Job Requirements')),
                ('created_date', models.DateTimeField(verbose_name='Creation Time')),
                ('modified_date', models.DateTimeField(verbose_name='Modified Time')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
