# Generated by Django 5.0.1 on 2024-01-13 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Candidate ID')),
                ('username', models.CharField(max_length=135, verbose_name='Candidate Name')),
                ('city', models.CharField(max_length=135, verbose_name='City')),
                ('phone', models.CharField(max_length=135, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='Email')),
                ('apply_position', models.CharField(blank=True, max_length=135, verbose_name='Apply Position')),
                ('born_address', models.CharField(blank=True, max_length=135, verbose_name='Location')),
                ('gender', models.CharField(blank=True, max_length=135, verbose_name='Gender')),
                ('candidate_remark', models.CharField(blank=True, max_length=135, verbose_name='Additional Info')),
                ('bachelor_school', models.CharField(blank=True, max_length=135, verbose_name='Bachelor')),
                ('master_school', models.CharField(blank=True, max_length=135, verbose_name='Master')),
                ('doctor_school', models.CharField(blank=True, max_length=135, verbose_name='Doctor')),
                ('major', models.CharField(blank=True, max_length=135, verbose_name='Major')),
                ('degree', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctor', 'Doctor')], max_length=135, verbose_name='Degree')),
                ('test_score_of_general_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Overall Score')),
                ('paper_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Paper Score')),
                ('first_score', models.DecimalField(blank=True, decimal_places=1, help_text='1-5，Excellent: >=4.5，Good: 4-4.4，Fair: 3.5-3.9，Average: 3-3.4，Poor: <3', max_digits=2, null=True, verbose_name='1st Round Score')),
                ('first_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Ability to Learn')),
                ('first_professional_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Professional Competence')),
                ('first_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantages')),
                ('first_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Concerns')),
                ('first_result', models.CharField(blank=True, choices=[('2nd Round', '2nd Round'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=256, verbose_name='First Round Results')),
                ('first_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='Recommended Positions')),
                ('first_remark', models.CharField(blank=True, max_length=135, verbose_name='First Round Remarks')),
                ('second_score', models.DecimalField(blank=True, decimal_places=1, help_text='1-5，Excellent: >=4.5，Good: 4-4.4，Fair: 3.5-3.9，Average: 3-3.4，Poor: <3', max_digits=2, null=True, verbose_name='2nd Round Score')),
                ('second_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Ability to Learn')),
                ('second_professional_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Professional Competence')),
                ('second_pursue_of_excellence', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Pursuit of Excellence')),
                ('second_communication_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Communication')),
                ('second_pressure_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Stress Management')),
                ('second_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantages')),
                ('second_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Concerns')),
                ('second_result', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=256, verbose_name='Second Round Results')),
                ('second_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='Recommended Position')),
                ('second_remark', models.CharField(blank=True, max_length=135, verbose_name='2nd Remarks')),
                ('hr_score', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Score')),
                ('hr_responsibility', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Responsibility')),
                ('hr_communication_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Communication')),
                ('hr_logic_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Logic')),
                ('hr_potential', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Potential')),
                ('hr_stability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Stability')),
                ('hr_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantages')),
                ('hr_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Concerns')),
                ('hr_result', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=256, verbose_name='HR Results')),
                ('hr_remark', models.CharField(blank=True, max_length=256, verbose_name='HR Remarks')),
                ('creator', models.CharField(blank=True, max_length=256, verbose_name='Creator')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Time')),
                ('last_editor', models.CharField(blank=True, max_length=256, verbose_name='Last Editor')),
                ('first_interviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='Interviewer')),
                ('hr_interviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='HR Interviewer')),
                ('second_interviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='Interviewer')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'db_table': 'candidate',
                'permissions': [('export', 'Can export candidate list'), ('notify', 'notify interviewer for candidate review')],
            },
        ),
    ]
